"""Rebuild project-derived cases and separate medium-size synthetic cases offline.

The reference oracle uses set closure and mutually reachable components, not
Ieum output. Cycle counts are asserted only for simple ring components.
"""
import argparse
import copy
import json
from pathlib import Path
import sys

from extract_imports import SOURCES, json_text
from workflow_support import ROOT, text_digest

MANIFEST_REAL = ROOT / "evaluation/real/manifest.json"


def closure(graph):
    reached = {node: set(targets) & graph.keys() for node, targets in graph.items()}
    for via in graph:
        for node in graph:
            if via in reached[node]:
                reached[node].update(reached[via])
    return reached


def reference(graph, layers):
    """For these unique, deduplicated module graphs only; fail on complex SCCs."""
    reachable = closure(graph)
    remaining = set(graph)
    cycles = []
    while remaining:
        node = min(remaining)
        component = {other for other in remaining if other in reachable[node] and node in reachable[other]}
        remaining.difference_update(component or {node})
        if not component:
            continue
        internal = {item: set(graph[item]) & component for item in component}
        if any(len(targets) != 1 for targets in internal.values()) or any(
            sum(node in targets for targets in internal.values()) != 1 for node in component
        ):
            raise ValueError("Complex cyclic component needs a manually specified diagnostic count")
        cycles.append(sorted(component))
    layer_graph = {node: set() for node in graph}
    for upper, lower in layers:
        if upper not in graph or lower not in graph or upper == lower:
            raise ValueError("Reference supports distinct declared layer endpoints only")
        layer_graph[upper].add(lower)
    descendants = closure(layer_graph)
    violations = sorted([lower, upper] for upper in graph for lower in descendants[upper]
                        if upper in reachable[lower])
    missing = sorted([node, target] for node, targets in graph.items() for target in targets if target not in graph)
    kinds = {key: value for key, value in {"cycle": len(cycles), "undefined_dependency": len(missing),
                                          "layer_violation": len(violations)}.items() if value}
    return kinds, {"cyclic_components": cycles, "undefined_edges": missing, "layer_violation_pairs": violations}


def source_text(graph, layers, name):
    lines = [f"# Generated by scripts/prepare_corpus.py: {name}"]
    for node in sorted(graph):
        deps = sorted(graph[node])
        lines.append("module " + node + (" depends " + ", ".join(deps) if deps else ""))
    lines += [f"layer {upper} above {lower}" for upper, lower in sorted(layers)]
    return "\n".join(lines) + "\n"


def dag_depth(graph):
    reached = closure(graph)
    if any(node in targets for node, targets in reached.items()):
        return None
    depths = {}

    def depth(node):
        if node not in depths:
            depths[node] = 1 + max((depth(target) for target in graph[node] if target in graph), default=0)
        return depths[node]

    return max((depth(node) for node in graph), default=0)


def products():
    cases, files, provenance = [], {}, []

    def add(name, graph, layers, group, origin, mutation, title, show=False):
        kinds, evidence = reference(graph, layers)
        source = f"evaluation/real/corpus/{name}.ieum"
        files[source] = source_text(graph, layers, name)
        layer_graph = {node: set() for node in graph}
        for upper, lower in layers:
            layer_graph[upper].add(lower)
        case = {"id": name, "source": source, "category": origin, "group": group,
                "expected_exit": int(bool(kinds)), "expected_kinds": kinds,
                "mutation": mutation, "reference_evidence": evidence,
                "review_status": "pending-human-review",
                "size": {"modules": len(graph), "dependencies": sum(map(len, graph.values())), "layers": len(layers)},
                "topology": {"dependency_dag_depth": dag_depth(graph), "layer_dag_depth": dag_depth(layer_graph)}}
        if show:
            case["graph"] = {"group": "examples", "title": title,
                             "note": "실제 프로젝트의 정적 import 투영" if origin.startswith("real") else
                                     "가독성 점검용 합성 구조 · 실제 프로젝트 표본에 포함하지 않음"}
        cases.append(case)

    specs = json.loads(SOURCES.read_text(encoding="utf-8"))["sources"]
    for spec in specs:
        name = spec["id"]
        path = ROOT / f"evaluation/real/snapshots/{name}.json"
        snapshot = json.loads(path.read_text(encoding="utf-8"))
        if snapshot["source"] != spec:
            raise ValueError(f"Source lock and snapshot disagree: {name}")
        mapping = {m["module"]: m["ieum"] for m in snapshot["modules"]}
        graph = {m["ieum"]: set(mapping[d] for d in m["dependencies"]) for m in snapshot["modules"]}
        provenance.append({"id": name, "snapshot": path.relative_to(ROOT).as_posix(),
                           "snapshot_sha256": text_digest(path), "repository": spec["repository"], "commit": spec["commit"]})
        add(name + "_original", graph, [], name, "real_original", None, name + " · 원본 구조", True)
        leaf = min(node for node, targets in graph.items() if not targets)
        missing = copy.deepcopy(graph)
        missing[leaf].add("missing_external_module")
        add(name + "_undefined", missing, [], name, "real_mutation",
            {"operation": "add_dependency", "from": leaf, "to": "missing_external_module"}, name + " · 미선언")
        cyclic = copy.deepcopy(graph)
        cyclic[leaf].add(leaf)
        add(name + "_self_cycle", cyclic, [], name, "real_mutation",
            {"operation": "add_dependency", "from": leaf, "to": leaf}, name + " · 자기 순환")
        upper, lower = (("itsdangerous__serializer", "itsdangerous__signer") if name == "itsdangerous" else
                        ("packaging___manylinux", "packaging___elffile"))
        if lower not in graph[upper]:
            raise ValueError(f"Policy reference edge missing: {name}")
        for suffix, pair, label in [("policy_forward", [upper, lower], "정방향 정책"),
                                    ("policy_reverse", [lower, upper], "역방향 정책")]:
            add(name + "_" + suffix, graph, [pair], name, "real_policy",
                {"operation": "add_layer_policy", "upper": pair[0], "lower": pair[1],
                 "basis": "Evaluation-only policy; not an upstream architectural constraint."},
                name + " · " + label, suffix == "policy_reverse")

    for count in (25, 50):
        graph = {f"m{i:02}": set() for i in range(count)}
        layers = []
        for base in range(0, count, 5):
            for level in range(4):
                upper, lower = f"m{base + level:02}", f"m{base + level + 1:02}"
                graph[upper].add(lower)
                layers.append([upper, lower])
            if base + 5 < count:
                graph[f"m{base:02}"].add(f"m{base + 5:02}")
        name = f"medium_{count}"
        add(name + "_valid", graph, layers, name, "synthetic", None, f"{count}개 모듈 · 정상", True)
        upper, lower = f"m{count - 5:02}", f"m{count - 1:02}"
        graph[lower].add(upper)
        add(name + "_cycle", graph, layers, name, "synthetic",
            {"operation": "add_dependency", "from": lower, "to": upper}, f"{count}개 모듈 · 순환·계층 위반", True)

    manifest = {"schema_version": 1,
                "scope": "Two pinned Python package projections and related mutations/policies; separate synthetic scale cases. Human review pending. Not runtime-import or population accuracy.",
                "review_status": "pending-human-review", "sources": provenance, "cases": cases}
    files[MANIFEST_REAL.relative_to(ROOT).as_posix()] = json_text(manifest)
    return files


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail on stale tracked corpus without rewriting")
    args = parser.parse_args()
    for relative, content in products().items():
        path = ROOT / relative
        if args.check:
            if path.read_text(encoding="utf-8") != content:
                raise ValueError(f"Stale generated artifact: {relative}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    print("Corpus verified" if args.check else "Corpus generated (14 cases, 2 real projects, 2 synthetic sizes)")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except (OSError, ValueError, KeyError) as error:
        print(f"Corpus error: {error}", file=sys.stderr)
        sys.exit(2)
